### ISSUE TITLE
Scatter view custom tooltip tries to format data before it is available (flaky)

### ISSUE THREAD

**Issue by vingkan** [scarletstudio/transithealth#92]
## Description

Sometimes, the community scatter view tries to apply the format function to data for a metric before that metric is actually received from the API response, which causes an error.

@wpj0110 and I noticed this while playing around with the app.

## To Reproduce

Warning: very flaky, hard to reproduce because it depends on timing.

- Hover over a point on the scatter plot to pull up the custom tooltip
- Start rapidly changing metrics from the selectors until you get this bug lol

## Expected Behavior

The scatter view should not try to format the metric until the data is loaded.

Maybe we need to have an intermediate loading state for the component.

**Comment by fabrego524** [comment]
During some pair programming with Vinesh, this was reproduced twice, once by accident and once intentionally. As mentioned in the initial post, it occurs when the tooltip is still present when changing the metric.

It seems this issue is specific to both 2010 and 2019 Median Income metrics, most likely to due with the way the currency unit is formatted. All other metrics simply display a `NaN` instead of the intended value.
